# Basic Site Settings
locale                   : "en-AU"
title                    : "June Luu"
title_separator          : "-"
name                     : &name "June Luu"
description              : &description "Business Analytics graduate specialising in business analysis, data analysis, and BI reporting."
url                      : https://JuneLuu48.github.io
baseurl                  : ""
repository               : "JuneLuu48/JuneLuu48.github.io"

# Site Author
author:
  avatar           : "https://static.wixstatic.com/media/c53cc1_d5b2f9a6a20049c299927c15a6185e32~mv2.jpg/v1/fill/w_1004,h_606,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/c53cc1_d5b2f9a6a20049c299927c15a6185e32~mv2.jpg"
  name             : "June Luu"
  pronouns         : "She/Her"
  bio              : "Business Analytics Graduate · Power BI · Python · SQL · Agile · Excel"
  location         : "Perth, Western Australia"
  email            : "buuquan2004@gmail.com"
  uri              : "https://juneluu48.github.io"
  github           : "JuneLuu48"
  linkedin         : "june-luu-55372227b"

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :
atom_feed:
  hide                   : true

# SEO
google_site_verification :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
 -  scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: false
      comment: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Australia/Perth

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
